version: 0.2
steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 7.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore RegistroNotas/RegistroNotas.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output RegistroNotas/RegistroNotas.csproj
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'
