# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
      #dotnet: latest - Latest resolve to 3.1, check this issue https://github.com/aws/aws-codebuild-docker-images/issues/414
    commands:
      - echo Installing Entity Framework Core tools reference - .NET CLI
      - echo Installing MySql.EntityFrameworkCore reference  - .NET CLI
      - echo Installing MySql.Data.EntityFrameworkCore reference  - .NET CLI
   
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet nuget locals all --clear
      - dotnet nuget locals global-packages --clear 
      - dotnet nuget locals http-cache --clear
      - dotnet restore
      - echo ASPNETCORE_ENVIRONMENT is $ASPNETCORE_ENVIRONMENT
      - echo $ConnectionStrings__DBContext
      - echo Info about dbcontext
      - dotnet ef dbcontext info
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build RegistroNotas/RegistroNotas.csproj
      - echo Test started on `date`
      - dotnet test RegistroNotas/RegistroNotas.csproj
      - echo Update database on `date`
      - dotnet ef database update
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 -o ./ RegistroNotas/RegistroNotas.csproj
      
artifacts:
  files:
    - ./**/*
