version: 0.2
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: 'sdk'
    version: '7.0.x'
    includePreviewVersions: true
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore RegistroNotas/RegistroNotas.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output RegistroNotas/RegistroNotas.csproj
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'
