// <auto-generated />
using DataBaseProyecto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBaseProyecto.Migrations
{
    [DbContext(typeof(EafitContext))]
    [Migration("20230320194343_DB.Init")]
    partial class DBInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataBaseProyecto.Models.Estudiante", b =>
                {
                    b.Property<int>("Id_Estudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id_Estudiante");

                    b.ToTable("Estudiante", (string)null);
                });

            modelBuilder.Entity("DataBaseProyecto.Models.Materia", b =>
                {
                    b.Property<int>("Id_Materia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id_Materia");

                    b.ToTable("Materia", (string)null);
                });

            modelBuilder.Entity("DataBaseProyecto.Models.Nota", b =>
                {
                    b.Property<int>("Id_Nota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Actividad")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Estudiante")
                        .HasColumnType("int");

                    b.Property<int>("Id_Materia")
                        .HasColumnType("int");

                    b.Property<double>("Porcentaje")
                        .HasColumnType("double");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id_Nota");

                    b.ToTable("Nota", (string)null);
                });

            modelBuilder.Entity("DataBaseProyecto.Models.Estudiante", b =>
                {
                    b.HasOne("DataBaseProyecto.Models.Nota", null)
                        .WithMany("Estudiante")
                        .HasForeignKey("Id_Estudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataBaseProyecto.Models.Materia", b =>
                {
                    b.HasOne("DataBaseProyecto.Models.Nota", null)
                        .WithMany("Materia")
                        .HasForeignKey("Id_Materia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataBaseProyecto.Models.Nota", b =>
                {
                    b.Navigation("Estudiante");

                    b.Navigation("Materia");
                });
#pragma warning restore 612, 618
        }
    }
}
